[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates
#[templates.placeholder]
#input_path = "/nix/store/3nq0kira5vrpa80kjbgfh574ias82aid-noctalia-shell-2025-11-21_f46915d/share/noctalia-shell/Assets/MatugenTemplates/noctalia.json"
#output_path = "/home/jeremiah/.cache/noctalia/placeholder.json"

